# Generated by Django 4.2.4 on 2023-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalender", "0003_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="use_type",
            field=models.CharField(
                choices=[("training", "Training"), ("lesson", "Reitstunde")],
                default="training",
                max_length=50,
            ),
        ),
    ]
