# Generated by Django 4.2.4 on 2024-01-31 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userinfo",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("mobil", models.CharField(blank=True, max_length=14, null=True)),
                ("street", models.CharField(blank=True, max_length=50, null=True)),
                ("street_nr", models.IntegerField(blank=True, null=True)),
                ("zip_code", models.IntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "self_description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
    ]
