# Generated by Django 4.2.4 on 2024-03-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={"verbose_name_plural": "Benutzer-Informationen"},
        ),
    ]
