# Generated by Django 4.2.4 on 2023-10-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="creation_time",
            new_name="creation_datetime",
        ),
    ]
