# Generated by Django 4.2.7 on 2023-11-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_creation_time_reservation_creation_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name_plural': 'Reservationen'},
        ),
    ]
