# Generated by Django 4.2.4 on 2023-09-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalender", "0004_event_use_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="use_type",
            field=models.CharField(
                choices=[("Training", "Training"), ("Reitstunde", "Reitstunde")],
                default="Training",
                max_length=50,
            ),
        ),
    ]
