# Generated by Django 4.2.4 on 2023-10-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="Material",
        ),
    ]
