# Generated by Django 4.2.4 on 2023-10-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0002_rename_task_material"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Material",
            new_name="Item",
        ),
    ]
