# Generated by Django 4.2.7 on 2023-11-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_rename_material_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Verbrauchsmaterial'},
        ),
    ]
