# Generated by Django 4.2.4 on 2023-10-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alp", "0002_alter_informationdetail_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="is_gallery_picture",
            field=models.BooleanField(default=False),
        ),
    ]
