# Generated by Django 4.2.4 on 2023-10-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alp", "0003_picture_is_gallery_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("phone", models.CharField(max_length=13)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name="picture",
            name="is_gallery_picture",
            field=models.BooleanField(default=False, verbose_name="Bild für Gallery"),
        ),
    ]
