# Generated by Django 4.2.4 on 2024-03-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alp", "0006_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="gives_permission",
            field=models.BooleanField(default=False),
        ),
    ]
